// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0wZi5eyny5Uogx9v8tuJ-dgc-Nu3dpE',
    appId: '1:241357483786:android:639c9f98aaebc9c5e614f3',
    messagingSenderId: '241357483786',
    projectId: 'integrador-13d3b',
    storageBucket: 'integrador-13d3b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJz3OFaT1q5N7oY_FosQ6w8jFx9W1NBsY',
    appId: '1:241357483786:web:3bc6514387f11509e614f3',
    messagingSenderId: '241357483786',
    projectId: 'integrador-13d3b',
    authDomain: 'integrador-13d3b.firebaseapp.com',
    storageBucket: 'integrador-13d3b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJz3OFaT1q5N7oY_FosQ6w8jFx9W1NBsY',
    appId: '1:241357483786:web:0aece8e212fa234ee614f3',
    messagingSenderId: '241357483786',
    projectId: 'integrador-13d3b',
    authDomain: 'integrador-13d3b.firebaseapp.com',
    storageBucket: 'integrador-13d3b.firebasestorage.app',
  );

}